/**
 * iReal Pro vs Our System: TypeScript 実コード比較
 *
 * 実際の generateBassLine() を呼び出して統計を収集し、
 * iReal Pro MIDI データと比較する。
 *
 * Usage: npx tsx scripts/compare_bass_ts.ts
 */

import { generateBassLine } from '../src/utils/bassPatterns';
import type { BackingStyle } from '../src/types';
import * as fs from 'fs';

// -------------------------------------------------------
// iReal Pro chord progressions (expanded, from parser)
// -------------------------------------------------------

interface ChordSpan {
  rootSemi: number;
  quality: string;
  beats: number;
  bassSemi: number | null; // slash chord bass note
}

const NOTE_PC: Record<string, number> = {
  C: 0, Db: 1, D: 2, Eb: 3, E: 4, F: 5,
  Gb: 6, G: 7, Ab: 8, A: 9, Bb: 10, B: 11,
};

// Pre-expanded chord progressions from parser output
// (generated by running parse_bass_phrases.py and extracting timeline)

function loadTimelines(): Record<string, ChordSpan[]> {
  const data = JSON.parse(fs.readFileSync('scripts/compare_timelines.json', 'utf-8'));
  return data;
}

// -------------------------------------------------------
// iReal Pro MIDI stats (pre-computed by Python)
// -------------------------------------------------------

interface IrealStats {
  intervals: number[];
  beat1Root: { root: number; nonRoot: number };
  beat1Midi: number[];
  approach: Record<number, number>;
  contour: { asc: number; desc: number; static: number };
}

function loadIrealStats(): IrealStats {
  return JSON.parse(fs.readFileSync('scripts/compare_ireal_stats.json', 'utf-8'));
}

// -------------------------------------------------------
// Simulate our system using actual TS code
// -------------------------------------------------------

function runSimulation(timelines: Record<string, ChordSpan[]>): {
  intervals: number[];
  beat1Root: { root: number; nonRoot: number };
  beat1Midi: number[];
  approach: Record<number, number>;
  contour: { asc: number; desc: number; static: number };
} {
  const intervals: number[] = [];
  const beat1Root = { root: 0, nonRoot: 0 };
  const beat1Midi: number[] = [];
  const approach: Record<number, number> = {};
  const contour = { asc: 0, desc: 0, static: 0 };

  for (const [song, timeline] of Object.entries(timelines)) {
    for (let ci = 0; ci < 30; ci++) {
      let prevLastMidi: number | null = null;

      for (let si = 0; si < timeline.length; si++) {
        const span = timeline[si];
        const nextSpan = si + 1 < timeline.length ? timeline[si + 1] : null;
        const refSemi = span.bassSemi ?? span.rootSemi;
        const nextRefSemi = nextSpan ? (nextSpan.bassSemi ?? nextSpan.rootSemi) : null;

        const globalBeatOffset = ci * timeline.reduce((s, c) => s + c.beats, 0)
          + timeline.slice(0, si).reduce((s, c) => s + c.beats, 0);

        const style: BackingStyle = 'medium-swing';
        const notes = generateBassLine(
          refSemi, span.quality, span.beats, nextRefSemi, style, globalBeatOffset,
        );

        if (notes.length === 0) continue;

        const firstMidi = notes[0].midi;
        const lastMidi = notes[notes.length - 1].midi;

        // Beat 1 register
        beat1Midi.push(firstMidi);

        // Beat 1 root check
        const firstSemi = (firstMidi - refSemi + 120) % 12;
        if (firstSemi === 0) beat1Root.root++;
        else beat1Root.nonRoot++;

        // Cross-chord interval
        if (prevLastMidi !== null) {
          intervals.push(Math.abs(firstMidi - prevLastMidi));
        }
        prevLastMidi = lastMidi;

        // Approach distance (4-beat, has next chord)
        if (span.beats >= 4 && nextRefSemi !== null) {
          const lastPC = lastMidi % 12;
          let d = Math.abs(lastPC - nextRefSemi) % 12;
          if (d > 6) d = 12 - d;
          approach[d] = (approach[d] || 0) + 1;
        }

        // Contour (4-beat, 4+ notes)
        if (span.beats === 4 && notes.length >= 4) {
          const p0 = notes[0].midi;
          const p3 = notes[3].midi;
          if (p3 > p0 + 1) contour.asc++;
          else if (p3 < p0 - 1) contour.desc++;
          else contour.static++;
        }
      }
    }
  }

  return { intervals, beat1Root, beat1Midi, approach, contour };
}

// -------------------------------------------------------
// Report
// -------------------------------------------------------

function report(label: string, stats: {
  intervals: number[];
  beat1Root: { root: number; nonRoot: number };
  beat1Midi: number[];
  approach: Record<number, number>;
  contour: { asc: number; desc: number; static: number };
}) {
  const arr = stats.intervals;
  const mean = arr.reduce((a, b) => a + b, 0) / arr.length;
  const sorted = [...arr].sort((a, b) => a - b);
  const median = sorted[Math.floor(sorted.length / 2)];
  const step = arr.filter(x => x <= 2).length / arr.length * 100;
  const within5th = arr.filter(x => x <= 7).length / arr.length * 100;
  const leap = arr.filter(x => x > 7).length / arr.length * 100;

  console.log(`  ${label}: mean=${mean.toFixed(1)}  med=${median}  step=${step.toFixed(0)}%  <=5th=${within5th.toFixed(0)}%  leap=${leap.toFixed(0)}%`);
}

// -------------------------------------------------------
// Main
// -------------------------------------------------------

async function main() {
  // Load bass phrase DB (simulate what loadBassPhraseDB does)
  const { loadBassPhraseDB } = await import('../src/utils/bassPatterns');
  // Mock fetch for Node.js
  const bassPhrasesJson = fs.readFileSync('public/bass-phrases.generated.json', 'utf-8');
  (globalThis as any).fetch = async (url: string) => {
    if (url.includes('bass-phrases')) {
      return { ok: true, json: async () => JSON.parse(bassPhrasesJson) };
    }
    if (url.includes('bass-config')) {
      const cfg = fs.readFileSync('public/bass-config.json', 'utf-8');
      return { ok: true, json: async () => JSON.parse(cfg) };
    }
    return { ok: false };
  };
  await loadBassPhraseDB();

  const timelines = loadTimelines();
  const irealStats = loadIrealStats();
  const ourStats = runSimulation(timelines);

  console.log('='.repeat(65));
  console.log('iReal Pro vs Our System (TS actual code)');
  console.log('='.repeat(65));

  console.log('\n--- 1. Cross-chord voice leading ---');
  report('iReal', irealStats);
  report('Ours ', ourStats);

  console.log('\n--- 2. Beat 1 start note ---');
  const irT = irealStats.beat1Root.root + irealStats.beat1Root.nonRoot;
  const siT = ourStats.beat1Root.root + ourStats.beat1Root.nonRoot;
  console.log(`  root      : iReal=${(irealStats.beat1Root.root / irT * 100).toFixed(1)}%  Ours=${(ourStats.beat1Root.root / siT * 100).toFixed(1)}%`);
  console.log(`  non-root  : iReal=${(irealStats.beat1Root.nonRoot / irT * 100).toFixed(1)}%  Ours=${(ourStats.beat1Root.nonRoot / siT * 100).toFixed(1)}%`);

  console.log('\n--- 3. Beat 1 register ---');
  const irMean = irealStats.beat1Midi.reduce((a, b) => a + b, 0) / irealStats.beat1Midi.length;
  const siMean = ourStats.beat1Midi.reduce((a, b) => a + b, 0) / ourStats.beat1Midi.length;
  console.log(`  iReal: mean=${irMean.toFixed(1)}  range=${Math.min(...irealStats.beat1Midi)}-${Math.max(...irealStats.beat1Midi)}`);
  console.log(`  Ours : mean=${siMean.toFixed(1)}  range=${Math.min(...ourStats.beat1Midi)}-${Math.max(...ourStats.beat1Midi)}`);

  console.log('\n--- 4. Beat 4 approach distance ---');
  const irAT = Object.values(irealStats.approach).reduce((a, b) => a + b, 0);
  const siAT = Object.values(ourStats.approach).reduce((a, b) => a + b, 0);
  console.log(`  D   iReal    Ours   Delta`);
  for (let d = 0; d < 7; d++) {
    const ir = (irealStats.approach[d] || 0) / irAT * 100;
    const si = (ourStats.approach[d] || 0) / siAT * 100;
    console.log(`  ${d}  ${ir.toFixed(1).padStart(5)}%  ${si.toFixed(1).padStart(5)}%  ${(si - ir >= 0 ? '+' : '') + (si - ir).toFixed(1).padStart(5)}%`);
  }

  console.log('\n--- 5. Contour direction (4-beat) ---');
  const irCT = irealStats.contour.asc + irealStats.contour.desc + irealStats.contour.static;
  const siCT = ourStats.contour.asc + ourStats.contour.desc + ourStats.contour.static;
  console.log(`  iReal: asc=${(irealStats.contour.asc / irCT * 100).toFixed(0)}%  desc=${(irealStats.contour.desc / irCT * 100).toFixed(0)}%  static=${(irealStats.contour.static / irCT * 100).toFixed(0)}%`);
  console.log(`  Ours : asc=${(ourStats.contour.asc / siCT * 100).toFixed(0)}%  desc=${(ourStats.contour.desc / siCT * 100).toFixed(0)}%  static=${(ourStats.contour.static / siCT * 100).toFixed(0)}%`);
}

main().catch(console.error);
